---
name: Update BSKY Starter Packs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_sp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Update Starter Packs
        run: uv run python src/starterpacks/update_starterpacks.py
        env:
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
